laravelbackend/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return view('welcome');});
Auth::routes();

//ADMIN RUTE
Route::group(['middleware' => ['web','admin']], function()
{
    Route::get('/cmsadmin/index', 'HomeController@index')->name('admin');
    Route::resource('/cmsadmin/tip_parcela', 'TipController'); //resource kreira sve rute, index, create, destroy, update, show, edit, store
    Route::resource('/cmsadmin/opis_parcela', 'OpisController');
    Route::resource('/cmsadmin/gost_kategorija', 'GostKategorijaController');
    Route::resource('/cmsadmin/usluga', 'UslugaController');
    Route::resource('/cmsadmin/parcela', 'ParcelaController');
    Route::resource('/cmsadmin/kazna', 'KaznaController');

    Route::get('/cmsadmin/korisnici', 'KorisniciController@index')->name('korisnik.index');
    Route::post('/cmsadmin/korisnici/{korisnik}/admin', 'KorisniciController@dodajadmin')->name('korisnik.dodajadmin');
    Route::post('/cmsadmin/korisnici/{korisnik}/kontrola', 'KorisniciController@dodajkontrola')->name('korisnik.dodajkontrola');
    Route::post('/cmsadmin/korisnici/{korisnik}/gost', 'KorisniciController@dodajgosta')->name('korisnik.dodajgosta');
});

//KONTROLOR RUTE
Route::group(['middleware' => ['web','campcontrol']], function()
{
    Route::get('/cmskontrola/index', 'HomeController@indexkontrola')->name('kontrola');
    Route::resource('/cmskontrola/kaznagostparcela', 'KaznaGostParcelaController'); //KAZNJAVANJE GOSTIJU

    Route::get('/cmskontrola/pregledgostparcela', 'GostParcelaController@indexpregled')->name('pregledgostparcela.index');
    Route::get('/cmskontrola/pregledgostparcela/pregled', 'GostParcelaController@pregled')->name('pregledgostparcela.pregled');
    Route::post('/cmskontrola/pregledgostparcela/{id}/edit', 'GostParcelaController@pregledano')->name('korisnik.pregledano');
});

//AUTH RUTE
Route::group(['middleware' => ['web','auth']], function()
{
    Route::get('/index', function () {return view('index');});   
});

Route::get('/logout', 'Auth\LoginController@logout'); //Auth::routes() kreira samo POST metodu za logout pa je moramo sami dodati za GET

laravelbackend/app/Kazna.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kazna extends Model
{
    protected $guarded=[];
}

laravelbackend/app/Http/Controllers/KaznaController.php
<?php

namespace App\Http\Controllers;

use App\Kazna;
use Illuminate\Http\Request;

class KaznaController extends Controller
{
    public function index()
    {
        return view('cmsadmin.kazna.index')->with('kazne', Kazna::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cmsadmin.kazna.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Kazna::create([
            'naziv'=>$request->naziv,
            'cijena'=>$request->cijena
        ]);

        return redirect(route('kazna.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Kazna $kazna)
    {
        return view ('cmsadmin.kazna.create')->with('kazna', $kazna);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Kazna $kazna)
    {
        $kazna->update([
            'naziv'=>$request->naziv,
            'cijena'=>$request->cijena,
        ]);
        return redirect(route('kazna.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Kazna $kazna)
    {
        $kazna->delete();
        return redirect(route('kazna.index'));
    }
}

laravelbackend/resources/views/cmsadmin/kazna/create.blade.php
@extends('cmsadmin.adminmaster')
@section('content')
<div class="col-md-8">
<div class="card card-defatult">
    <div class="card-header">
        {{ isset($kazna) ? 'Izmjeni KAZNU' : 'Kreiraj novu KAZNU'}}
    </div>
    <div class="card-body">
        <form action="{{ isset($kazna) ? route('kazna.update', $kazna->id) : route('kazna.store') }}" method="POST">
            @csrf
            @if(isset($kazna))
                @method('PUT')
            @endif
            <div class="form-group">
                <label for="naziv">Name</label>
                <input type="text" id="naziv" class="form-control" name="naziv" value="{{ isset($kazna) ? $kazna->naziv : ''}}">
            </div>
            <div class="form-group">
                <label for="cijena">Cijena</label>
                <input type="number" id="cijena" class="form-control" name="cijena" value="{{ isset($kazna) ? $kazna->cijena : ''}}">
            </div>
            @include('layouts.errors')
            <div class="form-group">
                <button class="btn btn-success">
                    {{ isset($kazna) ? 'Izmjeni KAZNU' : 'Dodaj KAZNU' }}
                </button>
            </div>
        </form>
    </div>
</div>
</div>
@endsection

laravelbackend/resources/views/cmsadmin/kazna/index.blade.php
@extends('cmsadmin.adminmaster')

@section('content')
<div class="d-flex justify-content-end mb-2">
<a href="{{ route('kazna.create') }}" class="btn btn-success">Dodaj novu KAZNU</a>
</div>
  <div class="card card-defatult">
    <div class="card-header">KAZNE GOSTIJU</div>
    @if($kazne->count()>0)
    <div class="card-body">
        <table class="table">
            <thead>
                <th>NAZIV</th>
                <th>CIJENA</th>
                <th></th>
            </thead>
            <tbody>
                @foreach($kazne as $kazna)
                    <tr>
                        <td>
                            {{ $kazna->naziv }}
                        </td>
                        <th>
                            {{ $kazna->cijena }} EUR
                        </th>
                        <td>
                            <a href="{{ route('kazna.edit', $kazna->id) }}" class="btn btn-info btn-sm">Edit</a>
                            <button class="btn btn-danger btn-sm" onclick="handleDelete({{ $kazna->id }})">Delete</button>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <form action="" method="POST" id="deleteKaznaForm">
    @method('DELETE')
    @csrf
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Kazna</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <p class="text-center text-bold">Želite li stvarno izbrisati podatak?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Ne, idi natrag.</button>
        <button type="submit" class="btn btn-danger">Da, izbriši.</button>
      </div>
    </div>
    </form>
  </div>
</div>
    </div>
</div>
@else
<div class="card-header" mt-5>
    <h4 class="text-center">Nema podataka o KAZNAMA.</h4>
    <h5 class="text-center">Molimo Vas, kreirajte KAZNU.</h5>
    </div>
@endif

@endsection

@section('scripts')
    <script>
        function handleDelete(id){
            var form=document.getElementById('deleteKaznaForm')
            form.action='/cmsadmin/kazna/'+id
            console.log('deleting', form)
            $('#deleteModal').modal('show')
        }
    </script>
@endsection