laravelbackend/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return view('welcome');});
Auth::routes();

//ADMIN RUTE
Route::group(['middleware' => ['web','admin']], function()
{
    Route::get('/cmsadmin/index', 'HomeController@index')->name('admin');
    Route::resource('/cmsadmin/tip_parcela', 'TipController'); //resource kreira sve rute, index, create, destroy, update, show, edit, store
    Route::resource('/cmsadmin/opis_parcela', 'OpisController');
    Route::resource('/cmsadmin/gost_kategorija', 'GostKategorijaController');
    Route::resource('/cmsadmin/usluga', 'UslugaController');
    Route::resource('/cmsadmin/parcela', 'ParcelaController');
    Route::resource('/cmsadmin/kazna', 'KaznaController');

    Route::get('/cmsadmin/korisnici', 'KorisniciController@index')->name('korisnik.index');
    Route::post('/cmsadmin/korisnici/{korisnik}/admin', 'KorisniciController@dodajadmin')->name('korisnik.dodajadmin');
    Route::post('/cmsadmin/korisnici/{korisnik}/kontrola', 'KorisniciController@dodajkontrola')->name('korisnik.dodajkontrola');
    Route::post('/cmsadmin/korisnici/{korisnik}/gost', 'KorisniciController@dodajgosta')->name('korisnik.dodajgosta');
});

//KONTROLOR RUTE
Route::group(['middleware' => ['web','campcontrol']], function()
{
    Route::get('/cmskontrola/index', 'HomeController@indexkontrola')->name('kontrola');
    Route::resource('/cmskontrola/kaznagostparcela', 'KaznaGostParcelaController'); //KAZNJAVANJE GOSTIJU

    Route::get('/cmskontrola/pregledgostparcela', 'GostParcelaController@indexpregled')->name('pregledgostparcela.index');
    Route::get('/cmskontrola/pregledgostparcela/pregled', 'GostParcelaController@pregled')->name('pregledgostparcela.pregled');
    Route::post('/cmskontrola/pregledgostparcela/{id}/edit', 'GostParcelaController@pregledano')->name('korisnik.pregledano');
});

//AUTH RUTE
Route::group(['middleware' => ['web','auth']], function()
{
    Route::get('/index', function () {return view('index');});   
});

Route::get('/logout', 'Auth\LoginController@logout'); //Auth::routes() kreira samo POST metodu za logout pa je moramo sami dodati za GET

laravelbackend/resources/views/cmsadmin/adminmaster.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>CMS - ISK</title>
    <!-- Scripts -->
    <style>
        .btn-info{
            color: #fff;
        }
        
    </style>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('css')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/cmsadmin/index') }}">
                    ADMINISTRATOR CMS 
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        AUTOKAMP APLIKACIJA
                    </ul>
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                     <a class="dropdown-item" href="#">
                                        My Profile
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        <main class="py-4">
        @auth
        <div class="container"> 
        @include('layouts.alerts')
        <div class="row">
            <div class="col-md-4">
                <ul class="list-gruop">
                    @if(auth()->user()->isAdmin())
                    <li class="list-group-item">
                        <a href="#">Korisnici</a>
                    </li><br>
                    @endif
                    <li class="list-group-item">
                        <a href="{{route('gost_kategorija.index')}}">Cijene po godinama</a>
                    </li>
                    <li class="list-group-item">
                        <a href="{{route('tip_parcela.index')}}">Tip Parcela</a>
                    </li>
                    <li class="list-group-item">
                        <a href="{{route('opis_parcela.index')}}">Opis Parcela</a>
                    </li>
                    <li class="list-group-item">
                        <a href="{{route('parcela.index')}}">Parcele</a>
                    </li>
                    <li class="list-group-item">
                        <a href="{{route('usluga.index')}}">Usluge</a>
                    </li>
                    <li class="list-group-item">
                        <a href="{{route('kazna.index')}}">Kazne</a>
                    </li>
                    <li class="list-group-item">
                        <a href="{{route('korisnik.index')}}">Upravljanje korisnicima</a>
                    </li>
                </ul>
                <ul class="list-gruop" mt-5>
                    <li class="list-group-item">
                        <a href="#">Pregled naplaćenih kazni //ToDo</a>
                    </li>
                </ul>
            </div> 
            
            @yield('succeslogin')
            <div>
            @yield('content')
            </div>
            </div>
            
        </div>
        @endauth
        </main>
    </div>
    
    <script src="{{ asset('js/app.js') }}" ></script> 
    @yield('scripts')
</body>
</html>

laravelbackend/resources/views/cmsadmin/index.blade.php
@extends('cmsadmin.adminmaster')

@section('succeslogin')
            <div class="col-md-8">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                <div class="card">
                <div class="card-header">Kontrolna ploča</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    Uspješno ste se prijavili u aplikaciju kao administrator!
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection
           