laravelbackend/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return view('welcome');});
Auth::routes();

//ADMIN RUTE
Route::group(['middleware' => ['web','admin']], function()
{
    Route::get('/cmsadmin/index', 'HomeController@index')->name('admin');
    Route::resource('/cmsadmin/tip_parcela', 'TipController'); //resource kreira sve rute, index, create, destroy, update, show, edit, store
    Route::resource('/cmsadmin/opis_parcela', 'OpisController');
    Route::resource('/cmsadmin/gost_kategorija', 'GostKategorijaController');
    Route::resource('/cmsadmin/usluga', 'UslugaController');
    Route::resource('/cmsadmin/parcela', 'ParcelaController');
    Route::resource('/cmsadmin/kazna', 'KaznaController');

    Route::get('/cmsadmin/korisnici', 'KorisniciController@index')->name('korisnik.index');
    Route::post('/cmsadmin/korisnici/{korisnik}/admin', 'KorisniciController@dodajadmin')->name('korisnik.dodajadmin');
    Route::post('/cmsadmin/korisnici/{korisnik}/kontrola', 'KorisniciController@dodajkontrola')->name('korisnik.dodajkontrola');
    Route::post('/cmsadmin/korisnici/{korisnik}/gost', 'KorisniciController@dodajgosta')->name('korisnik.dodajgosta');
});

//KONTROLOR RUTE
Route::group(['middleware' => ['web','campcontrol']], function()
{
    Route::get('/cmskontrola/index', 'HomeController@indexkontrola')->name('kontrola');
    Route::resource('/cmskontrola/kaznagostparcela', 'KaznaGostParcelaController'); //KAZNJAVANJE GOSTIJU

    Route::get('/cmskontrola/pregledgostparcela', 'GostParcelaController@indexpregled')->name('pregledgostparcela.index');
    Route::get('/cmskontrola/pregledgostparcela/pregled', 'GostParcelaController@pregled')->name('pregledgostparcela.pregled');
    Route::post('/cmskontrola/pregledgostparcela/{id}/edit', 'GostParcelaController@pregledano')->name('korisnik.pregledano');
});

//AUTH RUTE
Route::group(['middleware' => ['web','auth']], function()
{
    Route::get('/index', function () {return view('index');});   
});

Route::get('/logout', 'Auth\LoginController@logout'); //Auth::routes() kreira samo POST metodu za logout pa je moramo sami dodati za GET

laravelbackend/resources/views/cmsadmin/opis_parcela/create.blade.php
@extends('cmsadmin.adminmaster')
@section('content')
<div class="col-md-8">
<div class="card card-defatult">
    <div class="card-header">
        {{ isset($opis) ? 'Izmjeni OPIS' : 'Kreiraj novi OPIS'}}
    </div>
    <div class="card-body">
        <form action="{{ isset($opis) ? route('opis_parcela.update', $opis->id) : route('opis_parcela.store') }}" method="POST">
            @csrf
            @if(isset($opis))
                @method('PUT')
            @endif
            <div class="form-group">
                <label for="opis">Opis</label>
                <input type="text" id="opis" class="form-control" name="opis" value="{{ isset($opis) ? $opis->opis : ''}}">
            </div>
            @include('layouts.errors')
            <div class="form-group">
                <button class="btn btn-success">
                    {{ isset($opis) ? 'Izmjeni Opis' : 'Dodaj Opis' }}
                </button>
            </div>
        </form>
    </div>
</div>
</div>
@endsection

laravelbackend/resources/views/cmsadmin/opis_parcela/index.blade.php
@extends('cmsadmin.adminmaster')

@section('content')
<div class="d-flex justify-content-end mb-2">
    <a href="{{ route('opis_parcela.create') }}" class="btn btn-success">Dodaj novi OPIS</a>
    </div>
      <div class="card card-defatult">
        <div class="card-header">OPIS PARCELA</div>
        @if($opisi->count()>0)
        <div class="card-body">
            <table class="table">
                <thead>
                    <th>OPIS</th>
                    <th>BROJ PARCELA</th>
                    <th></th>
                </thead>
                <tbody>
                    @foreach($opisi as $opis)
                        <tr>
                            <td>
                                {{ $opis->opis }}
                            </td>
                            <th>
                               //ToDo
                            </th>
                            <td>
                                <a href="{{ route('opis_parcela.edit', $opis->id) }}" class="btn btn-info btn-sm">Edit</a>
                                <button class="btn btn-danger btn-sm" onclick="handleDelete({{ $opis->id }})">Delete</button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <form action="" method="POST" id="deleteOpisForm">
        @method('DELETE')
        @csrf
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Opis</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
          <p class="text-center text-bold">Želite li stvarno izbrisati podatak?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Ne, idi natrag.</button>
            <button type="submit" class="btn btn-danger">Da, izbriši.</button>
          </div>
        </div>
        </form>
      </div>
    </div>
        </div>
    </div>
    @else
    <div class="card-header" mt-5>
        <h4 class="text-center">Nema podataka o OPISIMA.</h4>
        <h5 class="text-center">Molimo Vas, kreirajte OPIS.</h5>
        </div>
    @endif
    
    @endsection
    
    @section('scripts')
        <script>
            function handleDelete(id){
                var form=document.getElementById('deleteOpisForm')
                form.action='/cmsadmin/opis_parcela/'+id
                console.log('deleting', form)
                $('#deleteModal').modal('show')
            }
        </script>
    @endsection