laravelbackend/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return view('welcome');});
Auth::routes();

//ADMIN RUTE
Route::group(['middleware' => ['web','admin']], function()
{
    Route::get('/cmsadmin/index', 'HomeController@index')->name('admin');
    Route::resource('/cmsadmin/tip_parcela', 'TipController'); //resource kreira sve rute, index, create, destroy, update, show, edit, store
    Route::resource('/cmsadmin/opis_parcela', 'OpisController');
    Route::resource('/cmsadmin/gost_kategorija', 'GostKategorijaController');
    Route::resource('/cmsadmin/usluga', 'UslugaController');
    Route::resource('/cmsadmin/parcela', 'ParcelaController');
    Route::resource('/cmsadmin/kazna', 'KaznaController');

    Route::get('/cmsadmin/korisnici', 'KorisniciController@index')->name('korisnik.index');
    Route::post('/cmsadmin/korisnici/{korisnik}/admin', 'KorisniciController@dodajadmin')->name('korisnik.dodajadmin');
    Route::post('/cmsadmin/korisnici/{korisnik}/kontrola', 'KorisniciController@dodajkontrola')->name('korisnik.dodajkontrola');
    Route::post('/cmsadmin/korisnici/{korisnik}/gost', 'KorisniciController@dodajgosta')->name('korisnik.dodajgosta');
});

//KONTROLOR RUTE
Route::group(['middleware' => ['web','campcontrol']], function()
{
    Route::get('/cmskontrola/index', 'HomeController@indexkontrola')->name('kontrola');
    Route::resource('/cmskontrola/kaznagostparcela', 'KaznaGostParcelaController'); //KAZNJAVANJE GOSTIJU

    Route::get('/cmskontrola/pregledgostparcela', 'GostParcelaController@indexpregled')->name('pregledgostparcela.index');
    Route::get('/cmskontrola/pregledgostparcela/pregled', 'GostParcelaController@pregled')->name('pregledgostparcela.pregled');
    Route::post('/cmskontrola/pregledgostparcela/{id}/edit', 'GostParcelaController@pregledano')->name('korisnik.pregledano');
});

//AUTH RUTE
Route::group(['middleware' => ['web','auth']], function()
{
    Route::get('/index', function () {return view('index');});   
});

Route::get('/logout', 'Auth\LoginController@logout'); //Auth::routes() kreira samo POST metodu za logout pa je moramo sami dodati za GET

laravelbackend/resources/views/cmskontrola/kaznagosta/create.blade.php
@extends('cmskontrola.adminmaster')
@section('content')
<div class="col-md-8">
<div class="card card-defatult">

    <div class="card-header">
        {{ isset($kaznagostparcela) ? 'Izmjeni PARCELU' : 'Kreiraj novu PARCELU'}}
    </div>
    
    <div class="card-body">
    
        <form action="{{ isset($kaznagostparcela) ? route('kaznagostparcela.update', $kaznagostparcela->id) : route('kaznagostparcela.store') }}" method="POST">
            @csrf

            @if(isset($kaznagostparcela))
                @method('PUT')
            @endif


            <div class="form-group">
                <label for="idKazna">Kazna</label>
                <select name="idKazna" id="idKazna" class="form-control">
                    @foreach($kazne as $kazna)
                        <option value="{{ $kazna->id }}"> {{ $kazna->naziv }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="idKontrola">Kontrolor</label>
                <select name="idKontrola" id="idKontrola" class="form-control">
                    @foreach($kontrolori as $kontrolor)
                        <option value="{{ $kontrolor->id }}">{{ $kontrolor->surname }} {{ $kontrolor->name }}</option>
                    @endforeach
                </select>
            </div>
            
            <div class="form-group">
                <label for="idGostParcela">Gost na Parceli</label>
                <select name="idGostParcela" id="idGostParcela" class="form-control">
                    @foreach($gostiparcela as $gostparcela)
                        <option value="{{ $gostparcela->id }}">{{ $gostparcela->parcela->brojParcela }}, {{ $gostparcela->gost->surname }}{{ $gostparcela->gost->name }}</option>
                    @endforeach
                </select>
            </div>
            

            @include('layouts.errors')
            
            <div class="form-group">
                <button class="btn btn-success">
                    {{ isset($kaznagostparcela) ? 'Izmjeni PARCELU' : 'Dodaj PARCELU' }}
                </button>
            </div>

        </form>
    
    </div>
</div>
</div>
@endsection

laravelbackend/resources/views/cmskontrola/kaznagosta/index.blade.php
@extends('cmskontrola.adminmaster')

@section('content')
<div class="d-flex justify-content-end mb-2">
<a href="{{ route('kaznagostparcela.create') }}" class="btn btn-success">Dodaj novi TIP</a>
</div>
  <div class="card card-defatult">
    <div class="card-header">TIP PARCELA</div>
    @if($kaznegostparcela->count()>0)
    <div class="card-body">
        <table class="table">
            <thead>
                <th>KAZNA</th>
                <th>GOST</th>
                <th>PARCELA</th>
                <th></th>
            </thead>
            <tbody>
                @foreach($kaznegostparcela as $kaznagostparcela)
                    <tr>
                        <td>
                            {{ $kaznagostparcela->kazna->naziv }}, {{ $kaznagostparcela->kazna->cijena }} EUR
                        </td>
                        <th>
                            {{ $kaznagostparcela->gostparcela->gost->surname }} {{ $kaznagostparcela->gostparcela->gost->name }}
                        </th>
                        <th>
                            {{ $kaznagostparcela->gostparcela->parcela->brojParcela }}
                        </th>
                        <td>
                            <a href="{{ route('kaznagostparcela.edit', $kaznagostparcela->id) }}" class="btn btn-info btn-sm">Edit</a>
                            <button class="btn btn-danger btn-sm" onclick="handleDelete({{ $kaznagostparcela->id }})">Delete</button>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <form action="" method="POST" id="deleteTipForm">
    @method('DELETE')
    @csrf
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Tip</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <p class="text-center text-bold">Želite li stvarno izbrisati podatak?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Ne, idi natrag.</button>
        <button type="submit" class="btn btn-danger">Da, izbriši.</button>
      </div>
    </div>
    </form>
  </div>
</div>
    </div>
</div>
@else
<div class="card-header" mt-5>
    <h4 class="text-center">Nema podataka o TIPOVIMA.</h4>
    <h5 class="text-center">Molimo Vas, kreirajte TIP.</h5>
    </div>
@endif

@endsection

@section('scripts')
    <script>
        function handleDelete(id){
            var form=document.getElementById('deleteTipForm')
            form.action='/cmskontrola/kaznagostparcela/'+id
            console.log('deleting', form)
            $('#deleteModal').modal('show')
        }
    </script>
@endsection